baseURL: "https://ankitts.github.io/"
title: Ankit
paginate: 5
theme: "PaperMod"
params:
    profileMode:
        enabled: true
        title: "Ankit Somani" # optional default will be site title
        subtitle: "Software Developer"
        imageUrl: "img/profile.jpg" # optional
        imageTitle: "Profile" # optional
        imageWidth: 180 # custom size
        imageHeight: 180 # custom size
        buttons:
            - name: CodeBlogs 
              url: "https://ankitts.github.io/bootstrap-codeblogs/"
            - name: LeetClone
              url: "https://leet-clone-murex.vercel.app/"
            - name: VibeSocial
              url: "https://spectacular-pavlova-3f9baf.netlify.app/"
            - name: ChatApp
              url: "https://vibe-chat-mu.vercel.app/"

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/ankitts"
        - name: "Twitter"
          url: "https://twitter.com/ankittsomani"
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/ankit-somani-172962214"
        - name: "Email"
          url: "mailto:ankitrsomani02@gmail.com"
